version: '3.4'

services:
  polychain:
    image: polychain
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8009:8009
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "server.js"]
